package com.web.carpool.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.ResponseBody;

import com.web.carpool.model.User;
import com.web.carpool.service.UserService;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/users") // This means URL's start with /users (after Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	@Qualifier("userService")
	private UserService userService;

	@GetMapping(path = "/id={id}")
	@ResponseBody
	public User getUserById(@PathVariable(value = "id") int userId) {
		// This returns a JSON or XML with the users
		return userService.findUserById(userId);
	}
	
	@GetMapping(path = "/username={username}")
	@ResponseBody
	public User getUserByUsername(@PathVariable(value = "username") String username) {
		return userService.findUserByUsername(username);
	}
	
	@GetMapping(path = "/email={email}")
	@ResponseBody
	public User getUserByEmail(@PathVariable(value = "email") String email) {
		return userService.findUserByEmail(email);
	}
	
	@GetMapping(path = "/all")
	public @ResponseBody List<User> getAllUsers() {
		return userService.findAll();
	}

	@PostMapping(path = "")
	public @ResponseBody User createUser(@RequestBody User user) {
		return userService.createUser(user);
	}
}
